const $=s=>document.querySelector(s), app=$('#app');
const stored=JSON.parse(localStorage.getItem('fengxiao-save')||'{"endings":[],"secret":false}');
let S={trust:0,clues:0,unity:0,h:0,chapter:0,flags:{},...stored};
const chars=[['任林楷','🦕'],['昆吧','🌻'],['仑吧','🌻'],['陈宇嘉','？'],['赛文','assets/saiwen-hero.png'],['张峻伟','assets/zhangjunwei-heige.png'],['张倡瑜','assets/zhangchangyu-zhangyu.jpg'],['邢庸','assets/xingyong-laoda.png'],['田俊辉','🏸'],['侯治嵘','assets/houzhirong-erye.jpg'],['牛敬博','assets/niujingbo-niu.jpg']];
function save(){localStorage.setItem('fengxiao-save',JSON.stringify({endings:S.endings||[],secret:S.secret||false}))}
function shell(inner){app.innerHTML=`<div class="shell"><div class="brand">047班</div>${inner}<div class="footer tiny">仅适配手机竖屏 · 你的选择会留下记录</div></div>`}
function menu(){const ends=(S.endings||[]);shell(`<section class="panel hero"><p class="muted">周五晚自习后，教学楼忽然停电。</p><h1>047班</h1><p>广播点名还没离校的你们：<br><span class="dialogue">“请前往旧实验楼。”</span></p><div class="badges"><span class="badge">已记录结局 ${ends.length}/5</span>${S.secret?'<span class="badge">隐藏章节已发现</span>':''}</div><button class="btn primary start" onclick="roster()">进入班级</button><button class="btn" onclick="records()">查看结局记录</button><button class="btn" onclick="resetGame()">重新开始一局</button></section>`)}
function roster(){shell(`<section class="panel"><h2>还没走的同学</h2><p class="muted">他们在同一个班。除此以外，你现在什么也不知道。</p><div class="card-grid">${chars.map(([n,v])=>`<div class="card">${v.includes('/')?`<img src="${v}" alt="${n}的视觉卡片">`:`<div class="portrait">${v}</div>`}<span>${n}</span></div>`).join('')}</div><button class="btn primary" onclick="start()">晚自习结束</button></section>`)}
function start(){S={trust:0,clues:0,unity:0,h:0,chapter:1,flags:{},endings:S.endings||[],secret:S.secret||false};scene('第一幕 · 广播','教室最后一盏灯闪了三次，整栋楼陷进黑暗。\n\n广播里传来失真的声音：\n<span class="dialogue">“请047班剩余同学，前往旧实验楼。”</span>\n\n任林楷把手机手电筒打开，赛文用课本卷了个临时扩音筒。侯治嵘顺手把门推开：“走吧，别让广播等急了。”牛敬博平静地补了一句：“它应该也没交作业。”大家刚笑出声，广播又重复了一遍，而且这次准确报出了你们所在的楼层。',[['先清点人数','至少别把同学落在黑暗里。',()=>{S.unity+=2;foyer()}],['检查广播时间','它似乎比你们的手表慢了三分钟。',()=>{S.clues++;foyer()}],['请田俊辉看看消息','他盯着亮起的屏幕，笑意忽然没了。',()=>{S.h++;foyer()}]])}
function foyer(){scene('第一幕 · 楼梯口','走廊应急灯亮了。地上的雨水从窗边缓缓漫过来，通往正门的楼梯挂着“施工中”的牌子。\n\n张峻伟把卡住的防火门扶住，侯治嵘催大家快走；张倡瑜刚伸手摸门把，就有人顺口喊了句“张倡偷”。\n\n陈宇嘉望着广播喇叭，轻轻来了一句：<span class="dialogue">“西里？”</span>',[['去旧实验楼查广播','声音似乎从那边传来。',()=>{S.clues++;S.unity++;gate()}],['先去保安室看记录','那里应该有校内通道图。',()=>{S.clues+=2;guard()}],['从体育馆找侧门','田俊辉记得还有一条路。',()=>{S.h++;gym()}]])}
function scene(title,text,choices){shell(`<div class="topline"><span>${title}</span><span>线索 ${S.clues} · 默契 ${S.unity}</span></div><section class="panel"><div class="scene">${text}</div>${choices.map((c,i)=>`<button class="choice" onclick="pick(${i})"><b>选择 ${'ABC'[i]}</b>${c[0]}<span class="tiny">${c[1]}</span></button>`).join('')}</section>`);window._choices=choices}
function pick(i){window._choices[i][2]()}
function gate(){scene('第二幕 · 锁住的门','旧实验楼门牌歪着。门缝里卡着一张新鲜的值班条：\n<span class="dialogue">“别单独行动。走廊地面有积水。”</span>\n\n灯光一闪，昆吧刚从转角走来。张倡瑜眯起眼，郑重其事地问他：<span class="dialogue">“你是昆吧？”</span>\n\n昆吧说：“不然呢？”仑吧在旁边笑得比谁都大声。',[['一起进去','保持队形。',()=>{S.unity+=2;twins()}],['让双胞胎先探路','他们说“我们很专业”。',()=>{S.clues++;S.unity--;twins(true)}],['先核对门上的纸条','纸角有值班室的印章。',()=>{S.clues+=2;S.unity++;twins()}]])}
function guard(){scene('第一幕 · 值班室','抽屉里有一本今天的记录：\n“22:10，已确认所有学生离校。”\n\n但你们明明还在。牛敬博看了一眼表，平静地说：“那我们集体算迟到，还是算提前到？”陈宇嘉站在门口，低声说：<span class="dialogue">“西里？”</span>\n\n最后一页写着：<span class="dialogue">“听到广播时，不要让他们走散。”</span>',[['把记录交给大家','先相信眼前的人。',()=>{S.trust++;S.unity+=2;twins()}],['悄悄收起来','信息越少越安全？',()=>{S.clues++;twins(true)}],['去体育馆核对广播来源','顺着电线找。',()=>{S.h++;gym()}]])}
function gym(){scene('第二幕 · 羽毛球馆','体育馆里只剩一束灯。田俊辉握着球拍：<span class="dialogue">“Me Si。”</span>\n\n球网另一侧没有人，却滚来一筒羽毛球。筒身贴着手写便条：“北侧小门已开，地面湿滑。”牛敬博读完，慢悠悠地说：“连神秘人都知道不能跑。”\n\n田俊辉悄悄把手机扣住。你瞥见消息只有两个字：<span class="dialogue">“别急。”</span>',[['让田俊辉试试北侧小门','有人似乎提前替他开了门。',()=>{S.h+=2;S.clues++;corridor()}],['让邢庸投向高处开关','他一球命中，灯亮了。',()=>{S.unity++;S.clues+=2;corridor()}],['大家先找防滑垫','安全第一，慢一点也行。',()=>{S.trust++;S.unity++;corridor()}]])}
function twins(split=false){scene('第二幕 · 两个昆吧',`楼道尽头站着一个同学。他说自己是昆吧。\n\n紧接着，另一个同学从另一头跑来，也说自己是昆吧。\n${split?'你忽然想起：刚才他们确实分开过。':'两张脸几乎一模一样。'}\n\n仑吧不见了。张倡瑜先开口：<span class="dialogue">“你是昆吧？”</span>\n\n左边那位气得跺脚；右边那位忍不住笑出声。原来仑吧把校服外套反穿了，想趁停电逗大家。侯治嵘一挥手：“好了，两位都归队。”`,[['再问昆吧一次','这回昆吧认真答了。',()=>{S.clues+=2;S.unity++;corridor()}],['把两人都拉回队伍','别让玩笑耽误赶路。',()=>{S.trust++;S.unity++;corridor()}],['请两人看走廊平面图','双胞胎一起指出近路。',()=>{S.unity+=2;S.clues++;corridor()}]])}
function corridor(){scene('第三幕 · 会说话的广播','大家在连廊碰头。广播突然传出陈宇嘉那声“西里？”，连停顿都一样。\n\n陈宇嘉抬起手机：三分钟前，他在班级群里发过一条语音；值班广播系统恰好接入了同一台旧电脑。\n\n更奇怪的是，屏幕上多了一个未发送的提示：<span class="dialogue">“别走南侧楼梯。”</span>',[['查看提示的来源','可能有人正在帮你们。',()=>{S.clues+=2;court()}],['让赛文照亮南侧楼梯','那里果然全是积水。',()=>{S.clues++;S.unity++;court()}],['请大家逐个回复位置','确认每个人都平安。',()=>{S.unity+=2;court()}]])}
function court(){scene('第三幕 · 操场脚印','操场湿漉漉的。巨大的脚印从旧楼一路通向广播室。\n\n张峻伟扶开一扇卡住的门；赛文举起手电，光里一闪而过的是橙黑相间的布料。\n\n田俊辉手机响了一下。他没看，先把它递给了门外一个模糊的人影。那人把伞往他这边偏了偏，自己半边肩膀淋在雨里。',[['沿脚印找干燥路面','别踩进积水。',()=>{S.clues++;evidence()}],['让所有人围成一圈走','谁也不落下。',()=>{S.unity+=2;evidence()}],['问那个人影是谁','田俊辉立刻说“没事”。',()=>{S.h+=2;evidence()}]])}
function evidence(){scene('第四幕 · 值班公告','广播室外的公告栏贴着一份临时通知：暴雨导致南侧楼梯渗水，今晚值班老师会引导剩余学生从北门离校。\n\n角落里还画着一个歪歪扭扭的虎头。原来那道橙黑影子是一件雨披。\n\n田俊辉把自己的伞塞给那个人影；对方把备用电池递回他手里。侯治嵘小声问：“那是H哥？”没人回答，但田俊辉把伞又往H哥那边推了推。',[['读完疏散路线','把刚才的怪事连起来。',()=>{S.clues++;radio()}],['提醒大家不要跑','老师可能就在里面。',()=>{S.unity++;radio()}],['等等他们两个','他们始终在照顾彼此。',()=>{S.h++;radio()}]])}
function radio(){scene('最终幕 · 广播室','广播室门口贴着一张手绘的疏散图。图上所有箭头都避开了积水和施工区。\n\n门开了。一位老师举着手电站在里面，外套上是橙黑条纹的雨披。\n\n<span class="dialogue">“我就知道，总有人会把安全演练玩成探险。”</span>\n\n原来“老虎”不是怪物。停电和暴雨让校内几处通道不安全，老师用广播把还没离校的你们引到这里。\n\n老师看着你们：<span class="dialogue">“现在，怎么回去？”</span>',[['按疏散图集体离开','听老师安排。',()=>finish(S.unity>=3?'默契疏散':'天亮前的集合')],['让邢庸用篮球打响信号铃','安全，但有点吵。',()=>finish('篮球导航')],['留下来确认田俊辉和那个人影','你感觉他们一直在互相照应。',()=>{if(S.h>=3) secret(); else finish('没说出口的照顾')}]] )}
function finish(name){if(!S.endings.includes(name))S.endings.push(name);save();shell(`<section class="panel hero"><p class="muted">结局已记录</p><h1>${name}</h1><div class="ending"><p>雨停时，你们跟着老师从安全通道离开。没有人受伤，也没有谁被落下。</p><p>老师最后回头说：“下次听广播，先别把它当成副本。”</p></div><button class="btn primary" onclick="matching()">揭晓绰号 · 开始匹配</button><button class="btn" onclick="menu()">回到首页</button></section>`)}
function secret(){S.secret=true;save();shell(`<section class="panel hero"><p class="muted">隐藏章节解锁</p><h1>两个人的决胜局</h1><p>老师给最后两人留了灯。田俊辉还在找球拍袋，H哥已经替他背上；H哥鞋带松了，田俊辉蹲下来，顺手系成了一个很夸张的蝴蝶结。</p><p>刚才那条“别急”，原来是H哥发的。备用电池、伞和北侧小门也是他一路准备的。田俊辉把最后一瓶水递给他，两个人谁都没说谢谢。</p><p>老师远远看见，只是笑着让他们快点跟上。</p><p class="dialogue">“Me Si。”<br>“嗯，我懂。”</p><button class="btn primary" onclick="finish('决胜局之后')">回到大家身边</button></section>`)}
const answers={'任林楷':'恐龙','昆吧':'哼哈二将','仑吧':'哼哈二将','陈宇嘉':'伪人','赛文':'奥特曼','张峻伟':'黑哥','张倡瑜':'章鱼','邢庸':'牢大','田俊辉':'日军','侯治嵘':'二爷','牛敬博':'牛'};
const matchEntries=Object.entries(answers).map(([name,nick],id)=>({id,name,nick}));
const matchOrder=[5,8,0,10,3,9,1,4,7,2,6];
let matchLinks={},activeName=null;
function matching(){matchLinks={};activeName=null;shell(`<section class="panel"><h2>你真的认识他们吗？</h2><p class="muted">先点左边姓名，再点右边绰号连线；点已连的姓名可以重选。两位双胞胎各有一张“哼哈二将”卡片。</p><div class="match-board"><svg class="match-lines" aria-hidden="true"></svg><div class="match-column">${matchEntries.map(e=>`<button class="match-tile" data-name="${e.id}" onclick="matchName(${e.id})" aria-label="姓名 ${e.name}">${e.name}</button>`).join('')}</div><div class="match-column">${matchOrder.map(id=>`<button class="match-tile" data-nick="${id}" onclick="matchNick(${id})" aria-label="绰号 ${matchEntries[id].nick}">${matchEntries[id].nick}</button>`).join('')}</div></div><p class="muted" id="matchCount">已连 0/${matchEntries.length}</p><button class="btn primary" onclick="checkMatch()">提交匹配</button><p id="matchMsg"></p></section>`)}
function matchName(id){if(matchLinks[id]!==undefined)delete matchLinks[id];activeName=id;updateMatching()}
function matchNick(id){if(activeName===null){$('#matchMsg').textContent='先点左边的姓名。';return}for(const key of Object.keys(matchLinks))if(matchLinks[key]===id)delete matchLinks[key];matchLinks[activeName]=id;activeName=null;$('#matchMsg').textContent='';updateMatching()}
function updateMatching(){document.querySelectorAll('[data-name]').forEach(el=>{let id=Number(el.dataset.name);el.classList.toggle('selected',id===activeName);el.classList.toggle('linked',matchLinks[id]!==undefined)});document.querySelectorAll('[data-nick]').forEach(el=>el.classList.toggle('linked',Object.values(matchLinks).includes(Number(el.dataset.nick))));$('#matchCount').textContent=`已连 ${Object.keys(matchLinks).length}/${matchEntries.length}`;drawMatchLines()}
function drawMatchLines(){const board=$('.match-board'),svg=$('.match-lines');if(!board||!svg)return;const box=board.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${box.width} ${box.height}`);svg.innerHTML=Object.entries(matchLinks).map(([nameId,nickId])=>{const left=board.querySelector(`[data-name="${nameId}"]`).getBoundingClientRect(),right=board.querySelector(`[data-nick="${nickId}"]`).getBoundingClientRect();const x1=left.right-box.left,y1=left.top+left.height/2-box.top,x2=right.left-box.left,y2=right.top+right.height/2-box.top;return `<path d="M${x1} ${y1} L${x2} ${y2}"/>`}).join('')}
window.addEventListener('resize',drawMatchLines);
function checkMatch(){const count=Object.keys(matchLinks).length,good=count===matchEntries.length&&Object.entries(matchLinks).every(([nameId,nickId])=>matchEntries[nameId].nick===matchEntries[nickId].nick);$('#matchMsg').innerHTML=good?'<span class="ok">全部正确！人物档案与🐯老师彩蛋已解锁。</span>':`<span class="error">${count<matchEntries.length?`还差 ${matchEntries.length-count} 条线。`:'还有几条线不对，再试试。'}</span>`;if(good){S.secret=true;save();setTimeout(archives,650)}}
function archives(){shell(`<section class="panel"><h2>人物档案 · 已解锁</h2><p class="muted">只有姓名与绰号；没有现实人物特征说明。</p><div class="card-grid">${Object.entries(answers).map(([n,k])=>`<div class="card"><span>${n}</span><small>${k}</small></div>`).join('')}<div class="card"><div class="portrait">🐯</div><span>老师</span><small>安全引导员</small></div></div><button class="btn primary" onclick="menu()">返回首页</button></section>`)}
function records(){shell(`<section class="panel hero"><h2>结局记录</h2><div class="log">${S.endings?.length?S.endings.map(x=>`✓ ${x}`).join('<br>'):'还没有结局。'}</div><button class="btn primary" onclick="roster()">开始新一局</button><button class="btn" onclick="menu()">返回</button></section>`)}
function resetGame(){S.endings=S.endings||[];menu()} menu();

